[package]
name = "filebrowser"
version = "0.1.0"
authors = ["sycration"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.2.0"
dirs = "3.0"